### ISSUE TITLE
Build GHA development practice

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [hackforla/engineering#31]
### Overview
We need org level GHAs across projects, and it would be useful to have some general HfLA guides about GHAs so that we can make running projects easier.

### Action Items
- [ ] Identify where the open GHAs will live
  - [ ] Review how the Data Science Community of Practice shares opportunities with their members
- [ ] How we will determine prioritization
- [ ] Who can submit
- [ ] Requirement drafting standards

### Resources/Instructions
- https://github.com/hackforla/admin/issues/52
- https://github.com/hackforla/engineering/issues/30

**Comment by ExperimentsInHonesty** [comment]
People in the conversation
Kevin Ashworth - returning, used to be on civictechindex
Matt Pereira - been here about a month on merge team at hfla
Will Gillis - been here about a month on hfla backend
Garth Tuazon - will be joining the website team been at the org for a week
Satenik - 
Mai Vang 
Seth - website team
Arpita Pandya - hfla since april, on merge team - backend
Justin Dingman - on merge team been here a few months - backend
Abraham website team 1 week
Yoojin - website team - 1 week
Travis - week hfla team - backend
Jessica - almost a year, on website 
Saumil - website team long time, full stack like backend
Ava Li, Civic tech jobs, also a backend developer 
Suman, website team 3 months - backend

**Comment by ExperimentsInHonesty** [comment]
Make an issue for determining feasibility of installing GHAs at the org level

**Comment by ExperimentsInHonesty** [comment]
Copy current instructions from Hack for LA website team and make it generic

**Comment by ExperimentsInHonesty** [comment]
Workshops we could run
- How the workflow works
- Syntax
- Command Line 
- Testing the GitHub Actions you have written (to reduce the time your testing takes)

**Comment by ExperimentsInHonesty** [comment]
Project board with each GHA that is ready to work on, or in progress of being written

**Comment by ExperimentsInHonesty** [comment]
- Proposed
- review
  - label: ready for quality review
  - label: need refinement
  - label: ready for prioritization
- ready for dev
- live beta
- released (done)
- will not do

**Comment by ExperimentsInHonesty** [comment]
Create a template issue for submitting a GHA proposal.  See https://github.com/hackforla/engineering/issues/30 and add anything you think is necessary

**Comment by JessicaLucindaCheng** [comment]
@JessicaLucindaCheng 
https://github.com/hackforla
/
[engineering](https://github.com/hackforla/engineering)
Public
generated from https://github.com/hackforla/.github
[Code](https://github.com/hackforla/engineering)
Issues
19
[Pull requests](https://github.com/hackforla/engineering/pulls)
[Discussions](https://github.com/hackforla/engineering/discussions)
[Actions](https://github.com/hackforla/engineering/actions)
Projects
5
[Wiki](https://github.com/hackforla/engineering/wiki)
More
Build GHA development practice #31
 Open
5 tasks
[ExperimentsInHonesty](https://github.com/ExperimentsInHonesty) opened this issue 14 days ago · 6 comments
 Open
5 tasks
[Build GHA development practice](https://github.com/hackforla/engineering/issues/31#top)
#31
[ExperimentsInHonesty](https://github.com/ExperimentsInHonesty) opened this issue 14 days ago · 6 comments
Comments
@ExperimentsInHonesty
Member
[ExperimentsInHonesty](https://github.com/ExperimentsInHonesty) commented [14 days ago](https://github.com/hackforla/engineering/issues/31#issue-1452563940) • 
Overview
We need org level GHAs across projects, and it would be useful to have some general HfLA guides about GHAs so that we can make running projects easier.

Action Items
 Identify where the open GHAs will live
 Review how the Data Science Community of Practice shares opportunities with their members
 How we will determine prioritization
 Who can submit
 Requirement drafting standards
Resources/Instructions
https://github.com/hackforla/admin/issues/52
https://github.com/hackforla/engineering/issues/30
https://github.blog/changelog/2022-01-21-share-github-actions-within-your-enterprise/
@ExperimentsInHonesty
Member
Author
[ExperimentsInHonesty](https://github.com/ExperimentsInHonesty) commented [14 days ago](https://github.com/hackforla/engineering/issues/31#issuecomment-1317957636)
People in the conversation
Kevin Ashworth - returning, used to be on civictechindex
Matt Pereira - been here about a month on merge team at hfla
Will Gillis - been here about a month on hfla backend
Garth Tuazon - will be joining the website team been at the org for a week
Satenik -
Mai Vang
Seth - website team
Arpita Pandya - hfla since april, on merge team - backend
Justin Dingman - on merge team been here a few months - backend
Abraham website team 1 week
Yoojin - website team - 1 week
Travis - week hfla team - backend
Jessica - almost a year, on website
Saumil - website team long time, full stack like backend
Ava Li, Civic tech jobs, also a backend developer
Suman, website team 3 months - backend

@ExperimentsInHonesty
Member
Author
[ExperimentsInHonesty](https://github.com/ExperimentsInHonesty) commented [14 days ago](https://github.com/hackforla/engineering/issues/31#issuecomment-1317980342) • 
Make an issue for determining feasibility of installing GHAs at the org level

Claimed by @Aveline-art

Aveline-art reacted with thumbs up emoji
Aveline-art reacted with rocket emoji
@ExperimentsInHonesty
Member
Author
ExperimentsInHonesty commented 14 days ago
Copy current instructions from Hack for LA website team and make it generic

@ExperimentsInHonesty
Member
Author
ExperimentsInHonesty commented 14 days ago
Workshops we could run

How the workflow works
Syntax
Command Line
Testing the GitHub Actions you have written (to reduce the time your testing takes)
@ExperimentsInHonesty
 
Add heading textAdd bold text, <Ctrl+b>Add italic text, <Ctrl+i>
Add a quote, <Ctrl+Shift+.>Add code, <Ctrl+e>Add a link, <Ctrl+k>
Add a bulleted list, <Ctrl+Shift+8>Add a numbered list, <Ctrl+Shift+7>Add a task list, <Ctrl+Shift+l>
Directly mention a user or teamReference an issue or pull request
Add saved reply
 The content you are editing has changed. Please copy your edits and refresh the page.

**Assigned to:** @JessicaLucindaCheng
**Progress:** Completed but pending review and getting questions answered
**Blockers**: Need a review and questions to be answered. 
**Availability:** 2 hours
**ETA:** Nov 30, 2022

### Tasks
- [x] Project board (using new projects and iterations) with each GHA that is ready to work on, or in progress of being written.
- [ ] Columns
  - [x]  Proposed
    - [ ] automated as to do
  - [x] Need product review
    - [x] label: ready for quality review
    - [x] label: needs refinement
    - [x] label: ready for prioritization
  - [x] ready for dev
  - [x] live beta
  - [x] released (done)
  - [x] will not do
- [ ] 

### Links
- [CoP Eng - GHAs project board](https://github.com/orgs/hackforla/projects/22/views/2)
  - [Workflows](https://github.com/orgs/hackforla/projects/22/workflows/4988940)
  - [Settings](https://github.com/orgs/hackforla/projects/22/settings) 
- [Labels](https://github.com/hackforla/engineering/labels?q=%22needs+refinement%22+OR+%22ready+for%22+)
  - ready for prioritization
  - needs refinement
  - ready for quality review 

### Questions and Review
- [x] Review labels
- [x] Review Project Board set up
  - [x] Question: Did you want an In Progress column? If not, where do devs put in progress issues? Yes, keep In Progress.
- [ ] Review Workflows
  - [x] Question: What do you mean by "automated as to do" for the "Proposed" column? See the website project board for what is in the automation
  - [x] Question: Are pull requests (PRs) going on the board too? If so, which columns? How does it work? No, don't put prs on the board. If a pr needs review, the associated issue should go in the `PR needs review` column.
  - [ ] Question: Do we want to auto-archive issues? No, we are just going to manually archive.
- [ ] Question: Do we want a wiki defining what goes in what columns and the process of how issues move through the columns? Yes
- [ ] Review Settings
  - [ ] Project Settings
    - [ ] Project name
    - [ ] Description
    - [x] README
      - [ ] Question: What, if anything, do you want in the README? Maybe wiki page if we decide to have one?
      - [ ] ReadMe should have an overview. With a link to the wiki (actually use mkdocs or docusaurus instead of the wiki). Replicate the mkdocs directory from https://github.com/hackforla/civictechjobs but make it only a docs folder, like https://github.com/codeforamerica/brigade-project-index (this is the associated website to it https://brigade.cloud/). 
    - Bonnie asked Ava will install mkdocs or docusaurus on the engineering repo.
- Notes: Separate repos for each GHAs but since this is the same as 100 Automations then we don't need separate repos but just use the 100 Automations process.
    - [ ] Visibility
      - Only organization owners can change project visibility. 
      - [ ] If you want to change it to public, the organization owner has to do it.
  - [ ] Manage access
    - [ ] Base role
    - [ ] Manage access
      - [ ] Question: What is the difference between `engineering-admin` and `engineering-maintain` teams?
        - [ ] Also, I don't see Ava on either of those teams.
      - [ ] Question: I am currently an Admin on the board since I created it and needed to edit Settings and other admin aspects of the board. Do you want me to remove myself as `Admin` after I am done setting up the board? I won't be able to make additional admin level edits to the board.
   - [ ] Custom fields
     - [ ] Status
     - [ ] Iteration
     - [ ] Estimate  
No file chosen
Attach files by dragging & dropping, selecting or pasting them.
Styling with Markdown is supported
@ExperimentsInHonesty
Member
Author
[ExperimentsInHonesty](https://github.com/ExperimentsInHonesty) commented [14 days ago](https://github.com/hackforla/engineering/issues/31#issuecomment-1317981298)
Create a template issue for submitting a GHA proposal. See #30 and add anything you think is necessary

@JessicaLucindaCheng

 
Add heading textAdd bold text, <Ctrl+b>Add italic text, <Ctrl+i>
Add a quote, <Ctrl+Shift+.>Add code, <Ctrl+e>Add a link, <Ctrl+k>
Add a bulleted list, <Ctrl+Shift+8>Add a numbered list, <Ctrl+Shift+7>Add a task list, <Ctrl+Shift+l>
Directly mention a user or team
Reference an issue, pull request, or discussion
Add saved reply
Leave a comment
No file chosen
Attach files by dragging & dropping, selecting or pasting them.
Styling with Markdown is supported
Remember, contributions to this repository should follow our GitHub Community Guidelines.
Assignees
No one—
Labels
None yet
Projects
None yet
Milestone
No milestone
Development
 for this issue or link a pull request.
Notifications
Customize
You’re receiving notifications because you’re watching this repository.
1 participant
@[ExperimentsInHonesty](https://github.com/ExperimentsInHonesty)

**Comment by Aveline-art** [comment]
Everything that can be done with a `.github` repo:

https://docs.github.com/en/organizations/collaborating-with-groups-in-organizations/customizing-your-organizations-profile
https://docs.github.com/en/actions/using-workflows/creating-starter-workflows-for-your-organization
https://docs.github.com/en/enterprise-cloud@latest/actions/using-workflows/sharing-workflows-secrets-and-runners-with-your-organization
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file

**Comment by ExperimentsInHonesty** [comment]
Links from last meeting
https://github.com/hackforla/engineering/labels?q=%22needs+refinement%22+OR+%22ready+for%22+
https://github.com/orgs/hackforla/projects/22/workflows
