### ISSUE TITLE
EPIC: Build wiki

### ISSUE THREAD

**Issue by mxajPrice** [hackforla/engineering#50]
### Overview
In #46 we outlined what we want in the Engineering wiki.  We will create an issue for each section of the wiki and track the progress here.  These pages are meant to be living documents so we only need to get the basics out.  We will continue to craft over time.

### Created wikis

- [ ] Welcome to the Eng CoP! #49
- [ ] About us
- [ ] How to join / perks of the community
- [ ] Programming
   - Speakers
   - Mentoring Nights
   - Lightning Talks
- [ ] Community
   - CoP Leads
   - Mentors
   - Completed Projects / Community Success Stories
   - Projects in Progress / volunteer opportunities
- [ ] Languages and Technologies
   - Technologies we use
   - Languages our community uses
- [ ] Resources
   - Software Development Lifecycle (SDLC) models - PLURAL
   - Guides and Templates
   - Related Repos and Wikis
- [ ] Donate to HfLA
