### ISSUE TITLE
Wiki page: Languages and Technologies

### ISSUE THREAD

**Issue by mxajPrice** [hackforla/engineering#54]
### Overview
We need a wiki page that shows what languages and technologies our engineers are using to build current HfLA products.  Along with listing those technologies, we should say which projects are using them.  

### Action Items
- [ ] Create a spreadsheet of projects and technologies and languages used
- [ ] Develop a section of the page for technologies used
- [ ] Develop a section of the page for languages used

### Resources/Instructions
[HfLA Projects](https://www.hackforla.org/projects/)
