### ISSUE TITLE
2023 Engineering CoP Agendas

### ISSUE THREAD

**Issue by mxajPrice** [hackforla/engineering#58]
### Overview
This issue tracks meeting agendas and summaries for the ENGINEERING COP meetings.
The schedule can be found [here](https://github.com/hackforla/engineering/wiki/CoP-Meetings#schedule).

### Agenda Quick-Links 
[16 November](https://github.com/hackforla/engineering/issues/58#issuecomment-1805007855) - Speaker:
[9 November](https://github.com/hackforla/engineering/issues/58#issuecomment-1782141180) - Networking Night
[26 October](https://github.com/hackforla/engineering/issues/58#issuecomment-1771958710) - Mentor Night
[24 August 2023](https://github.com/hackforla/engineering/issues/58#issuecomment-1683231491) - Speaker: Tim Malsted
[17 August 2023](https://github.com/hackforla/engineering/issues/58#issuecomment-1678313497) - Mentor Night
[10 August 2023](https://github.com/hackforla/engineering/issues/58#issuecomment-1654885461) - CANCELLED
[27 July 2023](https://github.com/hackforla/engineering/issues/58#issuecomment-1644913580) - Mentor Night
[20 July 2023](https://github.com/hackforla/engineering/issues/58#issuecomment-1635158987) - Speaker: Judson Lester
[13 July 2023](https://github.com/hackforla/engineering/issues/58#issuecomment-1615601563) - Lightning Talks
[29 June 2023](https://github.com/hackforla/engineering/issues/58#issuecomment-1603605872) - Open Networking
[22 June 2023](https://github.com/hackforla/engineering/issues/58#issuecomment-1594011712) - Mentor Night
[15 June 2023](https://github.com/hackforla/engineering/issues/58#issuecomment-1573046938) - Speaker: Sukrutha Ghadouria
[1 June 2023](https://github.com/hackforla/engineering/issues/58#issuecomment-1563726445) - Lightning Talks
[25 May 2023](https://github.com/hackforla/engineering/issues/58#issuecomment-1553916525) - Speaker: Jordan Harband
[18 May 2023](https://github.com/hackforla/engineering/issues/58#issuecomment-1548886995) - Mentor Night / Help Desk
[11 May 2023](https://github.com/hackforla/engineering/issues/58#issuecomment-1533863209) - Open Networking

**Comment by mxajPrice** [comment]
## 11 May - Engineering CoP meeting

### AGENDA
_Timezones listed as PDT._

- [ ] 18:00 _10 minutes_ - Welcome and Introductions
- [ ] 18:10 


#### FYIs


#### Notes from meeting


#### Task Items


#### Meeting Attendance

CoP Leads
- [ ] aj price
- [ ] Alejandro Gomez
- [ ] Harrison Katz
- [ ] Micah Elm

Engineers
- [ ]

**Comment by mxajPrice** [comment]
## 18 May - Mentor Night / Help Desk

### AGENDA
_Timezones listed as PDT._

- [ ] 18:00 - Rename yourself to [NAME | PROJECT]
- [ ] 18:00 _10 minutes_ - Mentor Introductions
   - What's your name?
   - How long have you been making software?
   - What projects are you working on right now?
- [ ] 18:10 _40 minutes_ - Project issues


#### QUESTIONS FOR MENTORS
- This is a sample question? -@mxajprice
- 

#### Notes from meeting


#### Task Items


#### Meeting Attendance

CoP Leads
- [ ] aj price
- [ ] Alejandro Gomez
- [ ] Harrison Katz
- [ ] Micah Elm

Mentors
- [ ] Adam Abundis
- [ ] Judson Lester
- [ ] Tony Delgado-Willis

Engineers
- [ ] Chelsey Beck
- [ ] Jason Ebueng
- [ ] Amath
- [ ] David Khan
- [ ] Keri Medeiros
- [ ] Krista Strucke
- [ ] Matt Pan
- [ ] Mitchell
- [ ] Seyi Zooms
- [ ] Tashiem Jameel
- [ ] Vardan Vanyan

**Comment by mxajPrice** [comment]
## 25 May - Speaker: Jordan Harband

### AGENDA
_Timezones listed as PDT._

- [ ] 18:00 _5 minutes_ - Welcome and Jordan introduction
   - Rename yourself to [NAME | PROJECT]
- [ ] 18:05 _30 minutes_ - Speaker
- [ ] 18:35 _10 minutes_ - Q&A
- [ ] 18:45 _5 minutes_ - Any Other Business (AOB)


#### Notes from meeting


#### Task Items


#### Meeting Attendance

CoP Leads
- [x] aj price
- [x] Alejandro Gomez
- [x] Harrison Katz
- [x] Micah Elm

Mentors
- [x] [Adam Abundis](https://github.com/abuna1985)
- [x] [Judson Lester](https://github.com/nyarly)
- [ ] [Tony Delgado-Willis](https://github.com/TonyDelgadoWillis)

Engineers
- [x] Chelsey Beck
- [x] Jason Ebueng
- [x] Belen
- [ ] Gibson Han
- [ ] 
- [ ] Amath | Website
- [ ] David Khan
- [ ] Keri Medeiros
- [ ] Krista Strucke
- [ ] Matt Pan
- [ ] Mitchell
- [ ] Seyi Zooms
- [ ] Tashiem Jameel
- [ ] Vardan Vanyan

**Comment by mxajPrice** [comment]
## 01 June - Lightning Talks

### AGENDA
_Timezones listed as PDT._

- [ ] 18:00 _5 minutes_ - Welcome and Lightning Talks introductions
   - Rename yourself to [NAME | PROJECT]
- [ ] 18:05 _10 minutes_ - Adam talk and questions
- [ ] 18:15 _10 minutes_ - 


#### Notes from meeting


#### Task Items


#### Meeting Attendance

CoP Leads
- [ ] aj price | Access the Data
- [ ] Alejandro Gomez | HfLA Website
- [ ] Harrison Katz
- [ ] Micah Elm | VRMS

Mentors
- [ ] [Adam Abundis](https://github.com/abuna1985) | Unassigned
- [ ] [Judson Lester](https://github.com/nyarly) | Access the Data
- [ ] [Tony Delgado-Willis](https://github.com/TonyDelgadoWillis) | Access the Data
- [ ] [Chelsey Beck](https://github.com/chelseybeck) | 311 Data

Engineers
- [ ] Amath | Website
- [ ] Belen | HfLA Website
- [ ] Chervonne Rachel | HfLA Website
- [ ] David Khan | People Depot
- [ ] Gibson Han
- [ ] Jason Ebueng | DevOps
- [ ] Jessica Chang | HfLA Website
- [ ] Katherine Kim
- [ ] Keri Medeiros
- [ ] Krista Strucke
- [ ] Matt Pan
- [ ] Matt Pereira | Civic Tech Jobs
- [ ] Mitchell
- [ ] Seyi Zooms | HfLA Website
- [ ] Tashiem Jameel | Unassigned
- [ ] Travis | HfLA Website
- [ ] Vardan Vanyan
- [ ] Ren Demeis-Ortiz | HfLA Website

**Comment by mxajPrice** [comment]
## 15 June - Lightning Talks

### AGENDA
_Timezones listed as PDT._

- [ ] 18:00 _15 minutes_ - Announcements
   - RENAME YOURSELF TO INCLUDE YOUR PROJECT
   - Bonnie time off
   - Code for America to [Civic Tech Structure](https://www.civictechstructure.org/) transition
      - [Draft sketch of new layout](https://user-images.githubusercontent.com/98370780/233212902-b91407e9-ba5e-453d-b5e4-44722a7b0d14.jpg)
   - Planning week, no CoP meetings next week
   - Security issues
   - Code of Conduct, escalating issues
   - Last week's talk recording has been posted in the wiki
- [ ] 18:15 _5 minutes_ - Welcome and Lightning Talks introductions
- [ ] 18:20 _10 minutes_ - Adam talk and questions
- [ ] 18:30 _5 minutes_ - AOB


#### Notes from meeting


#### Task Items


#### Meeting Attendance

CoP Leads
- [x] aj price | Access the Data
- [x] Alejandro Gomez | HfLA Website
- [x] Harrison Katz | Tables
- [ ] Micah Elm | VRMS

Mentors
- [x] [Adam Abundis](https://github.com/abuna1985) | Unassigned
- [ ] [Judson Lester](https://github.com/nyarly) | Access the Data
- [x] [Tony Delgado-Willis](https://github.com/TonyDelgadoWillis) | Access the Data
- [ ] [Chelsey Beck](https://github.com/chelseybeck) | 311 Data

Engineers
- [x] Aleksandr Binskiy
- [ ] Amath | Website
- [ ] Belen | HfLA Website
- [x] Chervonne Rachel | HfLA Website
- [x] David Khan | People Depot
- [ ] Emerson Castaneda
- [ ] Gibson Han
- [ ] Jason Ebueng | DevOps
- [ ] Jessica Chang | HfLA Website
- [ ] Jules
- [ ] Katherine Kim
- [ ] Keri Medeiros | HfLA Website
- [ ] Krista Strucke
- [x] Mark Wiltberger | HfLA Website
- [ ] Matt Pan | HfLA Website
- [ ] Matt Pereira | Civic Tech Jobs
- [ ] Mitchell
- [ ] Ren Demeis-Ortiz | HfLA Website
- [x] Seyi Akinwale | HfLA Website
- [ ] Tashiem Jameel | Unassigned
- [ ] Travis | HfLA Website
- [ ] Vardan Vanyan

**Comment by mxajPrice** [comment]
## 22 June - Mentor Night

### AGENDA
_Timezones listed as PDT._

- [ ] 18:00 _5 minutes_ - Welcome!
   - Rename yourself to [NAME | PROJECT]
   - Post your LinkedIn link in the chat
   - Post your main professional goal in the chat
- [ ] 18:05 _10 minutes_ - Mentor Introductions
   - What's your name?
   - What is your background in software?
   - What projects are you working on right now?
- [ ] 18:15 _30 minutes_ - Questions for mentors
- [ ] 18:45 _5 minutes_ - Any Other Business (AOB)


#### Notes from meeting


#### Task Items


#### Meeting Attendance

CoP Leads
- [ ] aj price | Access the Data
- [ ] Alejandro Gomez | HfLA Website
- [ ] Harrison Katz | Tables
- [ ] Micah Elm | VRMS

Mentors
- [ ] [Adam Abundis](https://github.com/abuna1985) | Unassigned
- [ ] [Judson Lester](https://github.com/nyarly) | Access the Data
- [ ] [Tony Delgado-Willis](https://github.com/TonyDelgadoWillis) | Access the Data
- [ ] [Chelsey Beck](https://github.com/chelseybeck) | 311 Data

Engineers
- [ ] Aleksandr Binskiy
- [ ] Amath | Website
- [ ] Belen | HfLA Website
- [ ] Chervonne Rachel | HfLA Website
- [ ] David Khan | People Depot
- [ ] Emerson Castaneda
- [ ] Gibson Han
- [ ] Jason Ebueng | DevOps
- [ ] Jessica Chang | HfLA Website
- [ ] Jules
- [ ] Katherine Kim
- [ ] Keri Medeiros | HfLA Website
- [ ] Krista Strucke
- [ ] Mark Wiltberger | HfLA Website
- [ ] Matt Pan | HfLA Website
- [ ] Matt Pereira | Civic Tech Jobs
- [ ] Mitchell
- [ ] Ren Demeis-Ortiz | HfLA Website
- [ ] Seyi Akinwale | HfLA Website
- [ ] Tashiem Jameel | Unassigned
- [ ] Travis | HfLA Website
- [ ] Vardan Vanyan

**Comment by mxajPrice** [comment]
## 29 June - Open Network
_[Back to Top](#)_

### AGENDA
_Timezones listed as PDT._

- [ ] 18:00 _5 minutes_ - Welcome!
   - Rename yourself to [NAME | PROJECT]
   - Post your LinkedIn link in the chat
- [ ] 18:05 _40 minutes_ - Discussion and drinks
- [ ] 18:45 _5 minutes_ - Any Other Business (AOB)


#### Notes from meeting
- Hot industry topics:
   - 

#### Task Items


#### Meeting Attendance

CoP Leads
- [ ] aj price | Access the Data
- [ ] Alejandro Gomez | HfLA Website
- [ ] Harrison Katz | Tables
- [ ] Micah Elm | VRMS

Mentors
- [x] [Adam Abundis](https://github.com/abuna1985) | Unassigned
- [x] [Judson Lester](https://github.com/nyarly) | Access the Data
- [ ] [Tony Delgado-Willis](https://github.com/TonyDelgadoWillis) | Access the Data
- [x] [Chelsey Beck](https://github.com/chelseybeck) | 311 Data

Engineers
- [ ] Aleksandr Binskiy
- [ ] Amath | Website
- [ ] Belen | HfLA Website
- [ ] Chervonne Rachel | HfLA Website
- [ ] David Khan | People Depot
- [ ] Emerson Castaneda
- [ ] Gibson Han
- [ ] Jason Ebueng | DevOps
- [ ] Jessica Chang | HfLA Website
- [ ] Jules
- [ ] Katherine Kim
- [ ] Keri Medeiros | HfLA Website
- [ ] Krista Strucke
- [ ] Mark Wiltberger | HfLA Website
- [ ] Matt Pan | HfLA Website
- [ ] Matt Pereira | Civic Tech Jobs
- [ ] Mitchell
- [ ] Ren Demeis-Ortiz | HfLA Website
- [ ] Seyi Akinwale | HfLA Website
- [ ] Tashiem Jameel | Unassigned
- [ ] Travis | HfLA Website
- [ ] Vardan Vanyan

**Comment by mxajPrice** [comment]
## 6 July - CANCELLED for planning week
_[Back to Top](#)_

**Comment by mxajPrice** [comment]
## 13 July - Lightning Talks
_[Back to Top](#)_

### AGENDA
_Timezones listed as PDT._

- [ ] 18:00 _5 minutes_ - Welcome!
   - Rename yourself to [NAME | PROJECT]
   - Post your LinkedIn link in the chat
- [ ] 18:05 _40 minutes_ - Lightning Talks
- [ ] 18:45 _5 minutes_ - Any Other Business (AOB)


#### Notes from meeting


#### Task Items


#### Meeting Attendance

CoP Leads
- [x] aj price | Access the Data
- [ ] Alejandro Gomez | HfLA Website
- [x] Harrison Katz | Tables
- [x] Micah Elm | VRMS

Mentors
- [ ] [Adam Abundis](https://github.com/abuna1985) | Unassigned
- [ ] [Judson Lester](https://github.com/nyarly) | Access the Data
- [ ] [Tony Delgado-Willis](https://github.com/TonyDelgadoWillis) | Access the Data
- [x] [Chelsey Beck](https://github.com/chelseybeck) | 311 Data

Engineers
- [x] Adrian Ang | HfLA Website
- [ ] Aleksandr Binskiy
- [ ] Amath | Website
- [ ] Belen | HfLA Website
- [ ] Chervonne Rachel | HfLA Website
- [ ] David Khan | People Depot
- [ ] Edgar U | Lucky Parking
- [ ] Emerson Castaneda
- [ ] Fang Liu | People Depot
- [ ] Gibson Han
- [ ] Hannah Zulueta | Food Oasis
- [ ] Jason Ebueng | DevOps
- [ ] Jen Alexander
- [ ] Jessica Cheng | HfLA Website
- [ ] Jose Padilla | HfLA Website
- [ ] Jules
- [ ] June Zhao | Food Oasis
- [ ] Katherine Kim
- [ ] Keri Medeiros | HfLA Website
- [ ] Krista Strucke
- [x] Mark Wiltberger | HfLA Website
- [x] Matt Pan | HfLA Website
- [ ] Matt Pereira | Civic Tech Jobs
- [ ] Mitchell
- [ ] Nicole Dubin
- [x] Paul Espinosa
- [ ] Phillip
- [ ] Ren Demeis-Ortiz | HfLA Website
- [x] Samuel Dallal
- [x] Saumil
- [ ] Seyi Akinwale | HfLA Website
- [ ] Tashiem Jameel | Unassigned
- [x] Travis | HfLA Website
- [ ] Vardan Vanyan
- [ ] Whitney | HfLA Website

**Comment by MicahBear** [comment]
## 15 June - Speaker: Judson Lester

### AGENDA
_Timezones listed as PDT._

- [ ] 18:00 _15 minutes_ - Announcements
   - RENAME YOURSELF TO INCLUDE YOUR PROJECT
- [ ] 18:15 _5 minutes_ - Welcome and Lightning Talks introductions
- [ ] 18:20 _10 minutes_ - 
- [ ] 18:30 _5 minutes_ - 


#### Notes from meeting


#### Task Items


#### Meeting Attendance

CoP Leads
- [x] aj price | Access the Data
- [x] Alejandro Gomez | HfLA Website
- [ ] Harrison Katz | Tables
- [x] Micah Elm | VRMS

Mentors
- [ ] [Adam Abundis](https://github.com/abuna1985) | Unassigned
- [x] [Judson Lester](https://github.com/nyarly) | Access the Data
- [ ] [Tony Delgado-Willis](https://github.com/TonyDelgadoWillis) | Access the Data
- [x] [Chelsey Beck](https://github.com/chelseybeck) | 311 Data

Engineers
- [x] Adrian Ang | HfLA Website
- [ ] Aleksandr Binskiy
- [x] Amath | Website
- [ ] Belen | HfLA Website
- [ ] Chervonne Rachel | HfLA Website
- [ ] David Khan | People Depot
- [ ] Edgar U | Lucky Parking
- [ ] Emerson Castaneda
- [ ] Fang Liu | People Depot
- [ ] Gibson Han
- [ ] Hannah Zulueta | Food Oasis
- [x] Jason Ebueng | DevOps
- [x] Jen Alexander
- [x] Jessica Cheng | HfLA Website
- [x] Jose Padilla | HfLA Website
- [x] Jules
- [ ] June Zhao | Food Oasis
- [ ] Katherine Kim
- [ ] Keri Medeiros | HfLA Website
- [ ] Krista Strucke
- [x] Mark Wiltberger | HfLA Website
- [ ] Matt Pan | HfLA Website
- [ ] Matt Pereira | Civic Tech Jobs
- [ ] Mitchell
- [x] Nicole Dubin
- [x] Paul Espinosa
- [x] Phillip
- [ ] Ren Demeis-Ortiz | HfLA Website
- [ ] Samuel Dallal
- [ ] Seyi Akinwale | HfLA Website
- [ ] Tashiem Jameel | Unassigned
- [x] Travis | HfLA Website
- [ ] Vardan Vanyan
- [x] Whitney | HfLA Website

**Comment by mxajPrice** [comment]
## 27 June - Mentor Night
_[Back to Top](#)_

### AGENDA
_Timezones listed as PDT._

- [ ] 18:00 _5 minutes_ - Welcome!
   - Rename yourself to [NAME | PROJECT]
   - Post your LinkedIn link in the chat
   - Post your main professional goal in the chat
- [ ] 18:05 _10 minutes_ - Mentor Introductions
   - What's your name?
   - What is your background in software?
   - What projects are you working on right now?
- [ ] 18:15 _30 minutes_ - Questions for mentors
- [ ] 18:45 _5 minutes_ - Any Other Business (AOB)


#### Notes from meeting


#### Task Items


#### Meeting Attendance

CoP Leads
- [x] aj price | Access the Data
- [x] Alejandro Gomez | HfLA Website
- [x] Harrison Katz | Tables
- [ ] Micah Elm | VRMS

Mentors
- [x] [Adam Abundis](https://github.com/abuna1985) | Unassigned
- [x] [Judson Lester](https://github.com/nyarly) | Access the Data
- [ ] [Tony Delgado-Willis](https://github.com/TonyDelgadoWillis) | Access the Data
- [x] [Chelsey Beck](https://github.com/chelseybeck) | 311 Data

Engineers

**Comment by mxajPrice** [comment]
## 10 August - Lightning Talks
_[Back to Top](#)_

### AGENDA
_Timezones listed as PDT._

- [ ] 18:00 _5 minutes_ - Welcome!
   - Rename yourself to [NAME | PROJECT]
   - Post your LinkedIn link in the chat
- [ ] 18:05 _15 minutes_ - Lightning Talks
    - 18:05 - 18:10 _5 minutes_
    - 18:10 - 18:15 _5 minutes_
    - 18:15 - 18:20 _5 minutes_
- [ ] 18:20 _30 minutes_ - Any Other Business (AOB)


#### Notes from meeting


#### Task Items


#### Meeting Attendance

CoP Leads
- [ ] aj price | Access the Data
- [x] Alejandro Gomez | TDM | HUU
- [ ] Harrison Katz | Tables
- [x] Micah Elm | VRMS

Mentors
- [ ] [Adam Abundis](https://github.com/abuna1985) | Unassigned
- [ ] [Judson Lester](https://github.com/nyarly) | Access the Data
- [ ] [Tony Delgado-Willis](https://github.com/TonyDelgadoWillis) | Access the Data
- [x] [Chelsey Beck](https://github.com/chelseybeck) | 311 Data

Engineers

**Comment by MicahBear** [comment]
## 17 August - TBD
_[Back to Top](#)_

### AGENDA
_Timezones listed as PDT._

- [ ] 18:00 _5 minutes_ - Welcome!
   - Rename yourself to [NAME | PROJECT]
   - Post your LinkedIn link in the chat
- [ ] 18:05 
- [ ] 18:45


#### Notes from meeting


#### Task Items


#### Meeting Attendance

CoP Leads
- [ ] aj price | Access the Data
- [ ] Alejandro Gomez | TDM | HUU
- [ ] Harrison Katz | Tables
- [ ] Micah Elm | VRMS

Mentors
- [ ] [Adam Abundis](https://github.com/abuna1985) | Unassigned
- [ ] [Judson Lester](https://github.com/nyarly) | Access the Data
- [ ] [Tony Delgado-Willis](https://github.com/TonyDelgadoWillis) | Access the Data
- [ ] [Chelsey Beck](https://github.com/chelseybeck) | 311 Data

Engineers

**Comment by mxajPrice** [comment]
## 20 July - Speaker: Tim Malsted
_[Back to Top](#)_

### AGENDA
_Timezones listed as PDT._

- [ ] 18:00 _05 minutes_ - Welcome
   - RENAME YOURSELF TO INCLUDE YOUR PROJECT
- [ ] 18:05 _30 minutes_ - Typescript talk
- [ ] 18:35 _10 minutes_ - Questions
- [ ] 18:45 _5 minutes_ - AOB


#### Notes from meeting


#### Task Items


#### Meeting Attendance

CoP Leads
- [x] aj price | Access the Data
- [x] Alejandro Gomez | HfLA Website
- [x] Harrison Katz | Tables
- [x] Micah Elm | VRMS

Mentors
- [ ] [Adam Abundis](https://github.com/abuna1985) | Unassigned
- [x] [Judson Lester](https://github.com/nyarly) | Access the Data
- [x] [Tony Delgado-Willis](https://github.com/TonyDelgadoWillis) | Access the Data
- [x] [Chelsey Beck](https://github.com/chelseybeck) | 311 Data

Engineers

**Comment by MicahBear** [comment]
## 31 August - 
_[Back to Top](#)_

### AGENDA
_Timezones listed as PDT._

- [ ] 18:00 _05 minutes_ - Welcome
   - RENAME YOURSELF TO INCLUDE YOUR PROJECT
- [ ] 18:05 _30 minutes_ - 
- [ ] 18:35 _10 minutes_ - 
- [ ] 18:45 _5 minutes_ - AOB


#### Notes from meeting


#### Task Items


#### Meeting Attendance

CoP Leads
- [ ] aj price | Access the Data
- [ ] Alejandro Gomez | HfLA Website
- [ ] Harrison Katz | Tables
- [ ] Micah Elm | VRMS

Mentors
- [ ] [Adam Abundis](https://github.com/abuna1985) | Unassigned
- [ ] [Judson Lester](https://github.com/nyarly) | Access the Data
- [ ] [Tony Delgado-Willis](https://github.com/TonyDelgadoWillis) | Access the Data
- [ ] [Chelsey Beck](https://github.com/chelseybeck) | 311 Data

**Comment by MicahBear** [comment]
## 31 August - Lightning Talks
_[Back to Top](#)_

### AGENDA
Host: @hkatzdev 
_Timezones listed as PDT._

- [ ] 18:00 _05 minutes_ - Welcome
   - RENAME YOURSELF TO INCLUDE YOUR PROJECT
   - Post your LinkedIn link in the chat
   - Open Lead positions
[Community Co-Lead](https://github.com/hackforla/engineering/wiki/Community-Leads-Open-Roles#engineering-cop-community-co-lead---mentor-coordinator)
[Engineering Mentors](https://github.com/hackforla/engineering/wiki/Community-Leads-Open-Roles#engineering-mentor-wanted)
- [ ] 18:05 _15 minutes_ - 
   - 18:05 - 18:10 5 minutes
   - 18:10 - 18:15 5 minutes
   - 18:15 - 18:20 5 minutes
- [ ] 18:20 _20 minutes_ - AOB


#### Notes from meeting


#### Task Items


#### Meeting Attendance

CoP Leads
- [ ] aj price | Access the Data
- [ ] Alejandro Gomez | HfLA Website
- [ ] Harrison Katz | Tables
- [ ] Micah Elm | VRMS

Mentors
- [ ] [Adam Abundis](https://github.com/abuna1985) | Unassigned
- [ ] [Judson Lester](https://github.com/nyarly) | Access the Data
- [ ] [Tony Delgado-Willis](https://github.com/TonyDelgadoWillis) | Access the Data
- [ ] [Chelsey Beck](https://github.com/chelseybeck) | 311 Data

Engineers

**Comment by chelseybeck** [comment]
## 14 September - Mentor Night
_[Back to Top](#)_

### AGENDA
_Timezones listed as PDT._

- [ ] 18:00 _5 minutes_ - Welcome!
   - Rename yourself to [NAME | PROJECT]
   - Post your LinkedIn link in the chat
   - Open Lead positions
      - [Mentor Coordinator](https://github.com/hackforla/engineering/wiki/Community-Leads-Open-Roles#engineering-cop-community-co-lead---mentor-coordinator)
      - [Engineering Mentors](https://github.com/hackforla/engineering/wiki/Community-Leads-Open-Roles#engineering-mentor-wanted)
- [ ] 18:05 _10 minutes_ - Mentor Introductions
   - What's your name?
   - What is your background in engineering?
   - What projects are you working on right now?
- [ ] 18:15 _30 minutes_ - Questions for mentors
- [ ] 18:45 _5 minutes_ - Any Other Business (AOB)


#### Notes from meeting


#### Task Items


#### Meeting Attendance

CoP Leads
- [ ] Chelsey Beck | People Depot
- [ ] Alejandro Gomez | TDM | HUU
- [x] Harrison Katz | Tables
- [x] Micah Elm | VRMS

Mentors
- [x] [Adam Abundis](https://github.com/abuna1985) | Unassigned
- [x] [Judson Lester](https://github.com/nyarly) | Access the Data
- [ ] [Tony Delgado-Willis](https://github.com/TonyDelgadoWillis) | Access the Data
- [x] [Chelsey Beck](https://github.com/chelseybeck) | 311 Data

Engineers

**Comment by MicahBear** [comment]
## 21 September - GCP DEMO 
_[Back to Top](#)_

### AGENDA
_Timezones listed as PDT._

- [x] 18:00 _5 minutes_ - Welcome!
   - Rename yourself to [NAME | PROJECT]
   - Post your LinkedIn link in the chat
- [x] 18:05 _45 minutes_ - GCP demo - Chelsey Beck



#### Notes from meeting


#### Task Items


#### Meeting Attendance

CoP Leads
- [x] Chelsey Beck | People Depot
- [x] Alejandro Gomez | TDM | HUU
- [x] Micah Elm | VRMS

Mentors
- [ ] [Adam Abundis](https://github.com/abuna1985) | Unassigned
- [ ] [Judson Lester](https://github.com/nyarly) | Access the Data
- [ ] [Tony Delgado-Willis](https://github.com/TonyDelgadoWillis) | Access the Data

**Comment by MicahBear** [comment]
## 28 September - Home United Us
_[Back to Top](#)_

### AGENDA
_Timezones listed as PDT._

- [x] 18:00 _05 minutes_ - Welcome
   - RENAME YOURSELF TO INCLUDE YOUR PROJECT
- [ ] 18:05 _30 minutes_ - AWS COGNITO
- [ ] 18:35 _10 minutes_ - Questions
- [ ] 18:45 _5 minutes_ - AOB


#### Notes from meeting


#### Task Items


#### Meeting Attendance

CoP Leads
- [ ] Chelsey Beck | People Depot
- [ ] Alejandro Gomez | HfLA Website
- [ ] Micah Elm | VRMS

Mentors
- [ ] [Adam Abundis](https://github.com/abuna1985) | Unassigned
- [ ] [Judson Lester](https://github.com/nyarly) | Access the Data
- [ ] [Tony Delgado-Willis](https://github.com/TonyDelgadoWillis) | Access the Data

**Comment by MicahBear** [comment]
## 12 October - Home Unite Us 
_[Back to Top](#)_

### AGENDA
Host: @agosmou 
_Timezones listed as PDT._

- [ ] 18:00 _05 minutes_ - Welcome
   - RENAME YOURSELF TO INCLUDE YOUR PROJECT
- [ ] 18:05 _35 minutes_ - AWS Cognito Demo
- [ ] 18:45 _5 minutes_ - AOB


#### Notes from meeting


#### Task Items


#### Meeting Attendance

CoP Leads
- [ ] Chelsey Beck | People Depot
- [ ] Alejandro Gomez | HfLA Website
- [ ] Micah Elm | VRMS

Mentors
- [ ] [Adam Abundis](https://github.com/abuna1985) | Unassigned
- [ ] [Judson Lester](https://github.com/nyarly) | Access the Data
- [ ] [Tony Delgado-Willis](https://github.com/TonyDelgadoWillis) | Access the Data

**Comment by agosmou** [comment]
## 19 October - Home Unite Us 
_[Back to Top](#)_

### AGENDA
Host: @agosmou 
_Timezones listed as PDT._

- [ ] 18:00 _05 minutes_ - Welcome
   - RENAME YOURSELF TO INCLUDE YOUR PROJECT
- [ ] 18:05 _35 minutes_ - Nick Taylor, Speaker Series
- [ ] 18:45 _15 minutes_ - Q&A


#### Notes from meeting


#### Task Items


#### Meeting Attendance

CoP Leads
- [ ] Chelsey Beck | People Depot
- [ ] Alejandro Gomez | HUU
- [ ] Micah Elm | VRMS

Mentors
- [ ] [Adam Abundis](https://github.com/abuna1985) | Unassigned
- [ ] [Judson Lester](https://github.com/nyarly) | Access the Data
- [ ] [Tony Delgado-Willis](https://github.com/TonyDelgadoWillis) | Access the Data
- [ ] Tim Malstead

**Comment by MicahBear** [comment]
## 26 September - Mentor Night (Halloween themed)
_[Back to Top](#)_

### AGENDA
_Timezones listed as PDT._

- [ ] 18:00 _5 minutes_ - Welcome!
   - Rename yourself to [NAME | PROJECT]
   - Post your LinkedIn link in the chat
   - Open Lead positions
      - [Mentor Coordinator](https://github.com/hackforla/engineering/wiki/Community-Leads-Open-Roles#engineering-cop-community-co-lead---mentor-coordinator)
      - [Engineering Mentors](https://github.com/hackforla/engineering/wiki/Community-Leads-Open-Roles#engineering-mentor-wanted)
- [ ] 18:05 _10 minutes_ - Mentor Introductions
   - What's your name?
   - What is your background in engineering?
   - What projects are you working on right now?
- [ ] 18:15 _30 minutes_ - Questions for mentors
- [ ] 18:45 _5 minutes_ - Any Other Business (AOB)


#### Notes from meeting


#### Task Items


#### Meeting Attendance

CoP Leads
- [ ] Chelsey Beck | People Depot
- [ ] Alejandro Gomez | TDM | HUU
- [ ] Micah Elm | VRMS

Mentors
- [ ] [Adam Abundis](https://github.com/abuna1985) | Unassigned
- [ ] [Judson Lester](https://github.com/nyarly) | Access the Data
- [ ] [Tony Delgado-Willis](https://github.com/TonyDelgadoWillis) | Access the Data
- [ ] [Chelsey Beck](https://github.com/chelseybeck) | People Depot
- [ ] Tim Malstead

Engineers

**Comment by MicahBear** [comment]
## 9 November- NETWORKING
_[Back to Top](#)_

### AGENDA
Host: Co-Lead 
_Timezones listed as PDT._

- [ ] 18:00 _05 minutes_ - Welcome
   - RENAME YOURSELF TO INCLUDE YOUR PROJECT
- [ ] 18:05 _55 minutes_ - Networking
- [ ] 18:45 _5 minutes_ - AOB


#### Notes from meeting


#### Task Items


#### Meeting Attendance

CoP Leads
- [ ] Chelsey Beck | People Depot
- [ ] Alejandro Gomez | HfLA Website
- [ ] Micah Elm | VRMS

Mentors
- [ ] [Adam Abundis](https://github.com/abuna1985) | Unassigned
- [ ] [Judson Lester](https://github.com/nyarly) | Access the Data
- [ ] [Tony Delgado-Willis](https://github.com/TonyDelgadoWillis) | Access the Data

**Comment by MicahBear** [comment]
## 16 November - Speaker : TBD
_[Back to Top](#)_

### AGENDA
Host: @agosmou 
_Timezones listed as PDT._

- [ ] 18:00 _05 minutes_ - Welcome
   - RENAME YOURSELF TO INCLUDE YOUR PROJECT
- [ ] 18:05 _35 minutes_ - Nick Taylor, Speaker Series
- [ ] 18:45 _15 minutes_ - Q&A


#### Notes from meeting


#### Task Items


#### Meeting Attendance

CoP Leads
- [ ] Chelsey Beck | People Depot
- [ ] Zeke Arany-Lucas | TDM
- [x] Alejandro Gomez | HUU
- [x] Micah Elm | VRMS

Mentors
- [ ] [Adam Abundis](https://github.com/abuna1985) | Unassigned
- [ ] [Judson Lester](https://github.com/nyarly) | Access the Data
- [ ] [Tony Delgado-Willis](https://github.com/TonyDelgadoWillis) | Access the Data
- [ ] Tim Malstead
