### ISSUE TITLE
Guest Speaker Question Tracker

### ISSUE THREAD

**Issue by MicahBear** [hackforla/engineering#61]
### Overview
Create issues that collect Engineering members' questions for guest speakers so that we can help guest speakers know how to prepare for their talks to Engineering Community of Practice.

### Action Items
- [x] Click on the link in the resources below to create a new issue
- [x] Fill out the bracketed information in the issue template
- [x] After the issue is created, add to the list created issues below

### Resources/Instructions
- [Create new issue for guest speaker questions](https://github.com/hackforla/engineering/issues/new?assignees=&labels=&projects=&template=guest_speaker_questions.md&title=Generate+Questions+for+%5BYYYY-MM-DD%5D%3A+%5BNAME%2FCOMPANY%5D)

### Created Issues
- #63 
- #67 
- #72

**Comment by MicahBear** [comment]
This issue is to keep track of all issues for the question issues that are generated for speakers.

**Comment by agosmou** [comment]
Created item for Sukrutha Bhadouria

**Comment by agosmou** [comment]
Created Issue for Judson Lester
